/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
          "surface-bright": "rgb(var(--color-surface-bright) / <alpha-value>)",
          "primary": "rgb(var(--color-primary) / <alpha-value>)",
          "on-tertiary": "rgb(var(--color-on-tertiary) / <alpha-value>)",
          "tertiary-fixed": "rgb(var(--color-tertiary-fixed) / <alpha-value>)",
          "on-background": "rgb(var(--color-on-background) / <alpha-value>)",
          "tertiary-fixed-dim": "rgb(var(--color-tertiary-fixed-dim) / <alpha-value>)",
          "outline": "rgb(var(--color-outline) / <alpha-value>)",
          "tertiary": "rgb(var(--color-tertiary) / <alpha-value>)",
          "secondary-fixed": "rgb(var(--color-secondary-fixed) / <alpha-value>)",
          "on-error": "rgb(var(--color-on-error) / <alpha-value>)",
          "primary-fixed-dim": "rgb(var(--color-primary-fixed-dim) / <alpha-value>)",
          "surface-container-lowest": "rgb(var(--color-surface-container-lowest) / <alpha-value>)",
          "background": "rgb(var(--color-background) / <alpha-value>)",
          "surface-container-highest": "rgb(var(--color-surface-container-highest) / <alpha-value>)",
          "secondary-container": "rgb(var(--color-secondary-container) / <alpha-value>)",
          "surface-variant": "rgb(var(--color-surface-variant) / <alpha-value>)",
          "on-primary-fixed-variant": "rgb(var(--color-on-primary-fixed-variant) / <alpha-value>)",
          "on-primary-fixed": "rgb(var(--color-on-primary-fixed) / <alpha-value>)",
          "tertiary-container": "rgb(var(--color-tertiary-container) / <alpha-value>)",
          "inverse-surface": "rgb(var(--color-inverse-surface) / <alpha-value>)",
          "on-tertiary-fixed": "rgb(var(--color-on-tertiary-fixed) / <alpha-value>)",
          "surface": "rgb(var(--color-surface) / <alpha-value>)",
          "surface-dim": "rgb(var(--color-surface-dim) / <alpha-value>)",
          "on-primary-container": "rgb(var(--color-on-primary-container) / <alpha-value>)",
          "on-surface": "rgb(var(--color-on-surface) / <alpha-value>)",
          "on-tertiary-fixed-variant": "rgb(var(--color-on-tertiary-fixed-variant) / <alpha-value>)",
          "primary-container": "rgb(var(--color-primary-container) / <alpha-value>)",
          "outline-variant": "rgb(var(--color-outline-variant) / <alpha-value>)",
          "on-secondary-fixed": "rgb(var(--color-on-secondary-fixed) / <alpha-value>)",
          "secondary": "rgb(var(--color-secondary) / <alpha-value>)",
          "surface-container-low": "rgb(var(--color-surface-container-low) / <alpha-value>)",
          "on-primary": "rgb(var(--color-on-primary) / <alpha-value>)",
          "on-secondary": "rgb(var(--color-on-secondary) / <alpha-value>)",
          "inverse-on-surface": "rgb(var(--color-inverse-on-surface) / <alpha-value>)",
          "secondary-fixed-dim": "rgb(var(--color-secondary-fixed-dim) / <alpha-value>)",
          "on-surface-variant": "rgb(var(--color-on-surface-variant) / <alpha-value>)",
          "primary-fixed": "rgb(var(--color-primary-fixed) / <alpha-value>)",
          "surface-container": "rgb(var(--color-surface-container) / <alpha-value>)",
          "on-secondary-fixed-variant": "rgb(var(--color-on-secondary-fixed-variant) / <alpha-value>)",
          "on-secondary-container": "rgb(var(--color-on-secondary-container) / <alpha-value>)",
          "surface-container-high": "rgb(var(--color-surface-container-high) / <alpha-value>)",
          "error-container": "rgb(var(--color-error-container) / <alpha-value>)",
          "surface-tint": "rgb(var(--color-surface-tint) / <alpha-value>)",
          "on-error-container": "rgb(var(--color-on-error-container) / <alpha-value>)",
          "inverse-primary": "rgb(var(--color-inverse-primary) / <alpha-value>)",
          "on-tertiary-container": "rgb(var(--color-on-tertiary-container) / <alpha-value>)",
          "error": "rgb(var(--color-error) / <alpha-value>)"
},
      "borderRadius": {
          "DEFAULT": "0.25rem",
          "lg": "0.5rem",
          "xl": "0.75rem",
          "full": "9999px"
      },
      "spacing": {
          "stack-lg": "24px",
          "stack-md": "16px",
          "stack-sm": "8px",
          "container-max-width": "1440px",
          "margin-tablet": "24px",
          "sidebar-width": "280px",
          "gutter": "24px",
          "margin-mobile": "16px",
          "margin-desktop": "32px"
      },
      "fontFamily": {
          "headline-lg": ["Inter"],
          "headline-md": ["Inter"],
          "headline-sm": ["Inter"],
          "body-lg": ["Inter"],
          "body-md": ["Inter"],
          "body-sm": ["Inter"],
          "label-md": ["Inter"],
          "label-sm": ["Inter"]
      },
      "fontSize": {
          "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
          "headline-md": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
          "headline-sm": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
          "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
          "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
          "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
          "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "600"}],
          "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.03em", "fontWeight": "600"}]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
